apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openvpn-manager.fullname" . }}-admin
  labels:
    {{- include "openvpn-manager.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.auth.jwtSecret | b64enc }}
  SLACK_BOT_TOKEN: {{ .Values.auth.slackBotToken | default "" | b64enc }}
