apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openvpn-manager.fullname" . }}-admin
  labels:
    {{- include "openvpn-manager.labels" . | nindent 4 }}
type: Opaque
data:
  ADMIN_USERNAME: {{ .Values.admin.username | b64enc }}
  ADMIN_PASSWORD: {{ .Values.admin.password | b64enc }}
  JWT_SECRET: {{ .Values.admin.jwtSecret | b64enc }}
  SLACK_BOT_TOKEN: {{ .Values.admin.slackBotToken | default "" | b64enc }}
