{{- if and .Values.sshKeys (not .Values.existingSshKeysSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openvpn-manager.fullname" . }}-ssh-keys
  labels:
    {{- include "openvpn-manager.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $name, $key := .Values.sshKeys }}
  {{ $name }}.pem: {{ $key | b64enc }}
  {{- end }}
{{- end }}
